apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/frontend:v0.10.7
        ports: 
        - containerPort: 8080
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - containerPort: 8080
    targetPort: 8080