apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: {{$.Values.services.adservice.replicas}}
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: "{{ $.Values.registry }}/adservice:{{ $.Values.tag }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports: 
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  selector:
    app: adservice
  ports:
  - port: 9555
    targetPort: 9555