apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: {{$.Values.services.adservice.replicas}}
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      serviceAccountName: adservice-sa
      containers:
      - name: adservice
        image: "{{ $.Values.registry }}/adservice:{{ $.Values.tag }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports: 
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  selector:
    app: adservice
  ports:
  - port: 9555
    targetPort: 9555

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: adservice-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: roleBinding
metadata:
  name: adservice-binding
subjects:
- kind: ServiceAccount
  name: adservice-sa
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io