registry: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo
tag: v0.10.7

services:
  adservice:
    replicas: 1
  cartservice:
    replicas: 1
  checkoutservice:
    replicas: 1
  currencyservice:
    replicas: 1
  emailservice:
    replicas: 1
  frontend:
    replicas: 3
  loadgenerator:
    replicas: 1
  paymentservice:
    replicas: 1
  productcatalogservice:
    replicas: 1
  recommendationservice:
    replicas: 1
  shippingservice:
    replicas: 1
